---
title: "Spatial taphonomy of the Early Pleistocene vertebrate locality of Tsiotra Vryssi, Mygdonia Basin, Greece"
subtitle: "Exploratory Data Analysis"
author: "Domenico Giusti"
bibliography: "../doc/manuscript/tsr_rr.bib"
output: 
  html_document: 
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval=TRUE, echo=FALSE, message=FALSE}
# load required packages
library(readxl)
library(ggplot2)
```

```{r, eval=TRUE, echo=FALSE, message=FALSE}
getwd()
```

## Reading and subsetting data

```{r, eval=FALSE, echo=FALSE}
# read TotalStation data
totalstation2015 <- read.csv("~/Dropbox/TSR_database/tsr_totalstation_2015.csv", header=TRUE, sep=",", skip=0)
totalstation2016 <- read.csv("~/Dropbox/TSR_database/tsr_totalstation_2016.csv", header=TRUE, sep=",", skip=0)
totalstation2017 <- read.csv("~/Dropbox/TSR_database/tsr_totalstation_2017.csv", header=TRUE, sep=",", skip=0)

totalstation_all <- rbind(totalstation2015, totalstation2016)
totalstation2017$spit <- as.integer(totalstation2017$spit)
totalstation2017$dip <- as.factor(totalstation2017$dip)
totalstation_all <- rbind(totalstation_all, totalstation2017)

write.csv(totalstation_all, "~/Dropbox/TSR/tsr_totalstation_all.csv")

totalstation_all <- read.csv("~/Dropbox/TSR/tsr_totalstation_all.csv", header=TRUE, sep=",", skip=0)

str(tsr_totalstation_all)

##
tsr_totalstation_all[1] <- NULL 
tsr_totalstation_all$id <- as.factor(tsr_totalstation_all$id)
tsr_totalstation_all$suffix <- as.factor(tsr_totalstation_all$suffix)
tsr_totalstation_all$spit <- as.factor(tsr_totalstation_all$spit)
tsr_totalstation_all$plunge <- gsub(pattern=" [A-Z]+$", replacement="", x=tsr_totalstation_all$plunge, ignore.case=FALSE)
tsr_totalstation_all$plunge <- as.integer(tsr_totalstation_all$plunge)
tsr_totalstation_all$date <- as.Date(tsr_totalstation_all$date, format="%m/%d/%Y")

summary(tsr_totalstation_all)
```

```{r, eval=FALSE, echo=FALSE}
# update
library(readxl)
fossil_list <- readxl::read_excel("~/Dropbox/TSR/tsr_fossil_list.xlsx", sheet=1, col_names=TRUE)


# read Konidaris shared Excel file (.xlsx)
tsr_fossil_list <- read_xlsx("~/Dropbox/TSR_database/tsr_fossil_list.xlsx", sheet = "TSR", col_names=TRUE, col_types=NULL)
write.csv(tsr_fossil_list, "./data/tsr_fossil_list.csv", na="NA")
tsr_fossil_list <- read.csv("./data/tsr_fossil_list.csv", header=TRUE, sep=",")
str(tsr_fossil_list)

tsr_fossil_list[1] <- NULL
tsr_fossil_list$year <- as.factor(tsr_fossil_list$year)
tsr_fossil_list$suffix <- as.factor(tsr_fossil_list$suffix)

summary(tsr_fossil_list)
```

```{r}
## merge the 2 datasets
X <- merge(tsr_totalstation_all, tsr_fossil_list, by=c("unit","id","suffix"), all.y=TRUE)
```

## EDA

```{r}
## subset stratified specimens with distinctive coordinates - no bucket finds - from Geo 4 (the filter is excluding finds from 2014 as well)
X <- subset(X, stratified.surface == "stratified" & geo.y == "4") 

# subset record with no coordinates
X <- subset(X, !is.na(X$x))
X <- subset(X, X$type.x != "Collected finds")
# subset fossil remains: exclude 1 coprolites, 2 micromammals
X <- subset(X, type.y %in% c("Bone","Bone/Tooth","Tooth"))
X$type.y <- factor(X$type.y)

summary(X)
plot(-X$y, X$x)
write.csv(X, "./data/X.csv", na="NA")

# select records within the window -> tsr_spR_geostatistics
X.df <- as.data.frame(X.sp)
write.csv(X.df, "./data/X.df.csv", na="NA")
summary(X.df)
plot(X.df$mx, X.df$my)

# Y is for faunal analysis only, X for spatial taphonomy
# select only mammals and NA for faunal analysis
Y <- X.df 
summary(Y)
Y <- subset(Y, Y$marks.class == "Mammalia")
write.csv(Y, "./data/Y.csv", na="NA")
```

### Spatial distribution

```{r}
# read shapefile of the contact between geo 3 and 4
geo3.4 <- readOGR("./data/shp/", layer="projected_Geo3.4_contact")
geo3.4 <- tidy(geo3.4)

# read shapefile of the excavation area
win <- rgdal::readOGR("./data/shp/bbox.shp")
win <- tidy(win)
```

#### Fig.4

```{r}
# fig.3a projected (x) vertical distribution of finds
summary(X.sp)

a <- ggplot() + geom_line(data=geo3.4, aes(long,lat), color="grey") + scale_x_reverse() + coord_fixed(ratio=2) + xlab("y") + ylab("z") + theme_bw() + ggtitle("a") + geom_point(data=X.df[which(X.df$marks.type.y %in% c("Bone","Bone/Tooth","Tooth")),], aes(x=-mx, y=marks.z.x, color=factor(marks.type.y), shape=factor(marks.integrity))) + scale_shape_manual(values=c(19,1)) + theme(legend.position="none")
a

# fig.7 horizontal spatial distribution of fossils
b <- ggplot() + geom_polygon(data=win, aes(lat,long), color="grey", fill="white", alpha=.3) + scale_x_reverse() + coord_fixed() + xlab("y") + ylab("x") + theme_bw() + ggtitle("b") + geom_point(data=X.df[which(X.df$marks.type.y %in% c("Bone","Bone/Tooth","Tooth")),], aes(x=-mx, y=my, color=factor(marks.type.y), shape=factor(marks.integrity))) + scale_shape_manual(values=c(19,1)) + theme(legend.title=element_blank(), legend.position=c(.93,.95))
b

setEPS()

pdf("./doc/manuscript/artwork/Fig:map_b.pdf", width=7.48, family="Helvetica")

#postscript("./artwork/Fig.eps", width=20, height=20, family="Helvetica")

par(mar= c(6,6,6,6), ps=7, cex=1, cex.main=2, cex.axis=1, cex.lab=1)
par(ps=7, cex=1, cex.main=2, cex.axis=1, cex.lab=1)

multiplot(a, b, rows=2)

dev.off()
```

### Taxonomy

#### Fig.10a

```{r}
# a) Distribution at the family level of the whole sampled material
a <- ggplot(Y, aes(x=marks.family)) + geom_bar() + coord_flip() + scale_x_discrete(limits=c(NA,"Equidae","Bovidae","Cervidae","Rhinocerotidae","Elephantidae","Ursidae","Canidae","Giraffidae"))+ theme_bw() + theme(axis.title.y = element_blank()) + ggtitle("a")
a
```

### Taphonomy

#### Fig.10b

```{r}
# b) Voorhies Groups distribution of the complete, isolated macromammal bones (plus rami of mandibles and maxillae) by body mass (BM)
b <- ggplot(data=Y[which(Y$marks.voorhies.group %in% c("I","I/II","II","II/III","III")),], aes(x=marks.voorhies.group)) + geom_bar() + facet_wrap(~marks.BM.category, ncol=1) + theme_bw() + theme(axis.title.x = element_blank()) + ggtitle("b")
b
```

#### Fig.10c

```{r}
# back-to-back plot
## isolated Mammal spec., not Voorhies (frags + teeth, antler)
foo <- Y[-which(Y$marks.voorhies.group %in% c("I","I/II","II","II/III","III")),]
foo <- foo[which(foo$marks.articulation == "isolated" & foo$marks.nsp.total != "?"),] 
summary(foo)

## Voorhies: isolated, complete Mammal spec.
bar <- Y[which(Y$marks.voorhies.group %in% c("I","I/II","II","II/III","III")),]
summary(bar)

baz <- rbind(foo, bar)
summary(baz)

### updated file baz (24 Sept. 2018)
write.csv(baz, "./data/Fig10c_baz.csv")
baz2 <- read.csv("./data/Fig10c_baz.csv", header=TRUE, sep=",", skip=0)

# c) Side-by-side distribution of complete/fragmented isolated macromammal skeletal elements
c <- ggplot(data=baz2, aes(x=Fig10c.skeletal.element)) + geom_bar(data=subset(baz2, marks.integrity == "fragment")) + geom_bar(data=subset(baz2, marks.integrity == "complete"), aes(y=..count..*(-1))) + coord_flip() + theme_bw() + theme(axis.title.y = element_blank()) + scale_x_discrete(limits=c(NA,"long bone frag.","phalanx","metapode","carpal/tarsal/sesamoid","tibia","rotule","femur","pelvis","ulna","radius","humerus","scapula","rib","vertebra","tooth","mandible","antler","cranium")) + scale_y_continuous(breaks=seq(-150,150,50), labels=abs(seq(-150,150,50))) + ggtitle("c")
c
```

#### Fig.10d

```{r}
# frequency distribution of articulated specimens (skeletal element) from Geo 4
foo <- Y[-which(Y$marks.voorhies.group %in% c("I","I/II","II","II/III","III")),]
foo <- foo[which(foo$marks.articulation == "articulated" & foo$marks.type.y == "Bone" & foo$marks.skeletal.part != "?complete"),]
summary(foo)

# d) Skeletal region distribution of articulated macromammal specimens
d <- ggplot(data=foo, aes(x=marks.skeletal.part)) + geom_bar() + theme_bw() + theme(axis.title.x = element_blank()) + scale_x_discrete(limits=c("appendicular","axial")) + ggtitle("d")
d
```

#### Multiplot

```{r}
# Fig. (double column - full page width: 190mm/539pt/7.48inches; lettering: 7pt)
setEPS()

pdf("./doc/manuscript/artwork/Fig:fauna_.pdf", width=7.48, height=7.48, family="Helvetica")

#postscript("./artwork/Fig.eps", width=20, height=20, family="Helvetica")

par(mar= c(6,6,6,6), ps=7, cex=1, cex.main=2, cex.axis=1, cex.lab=1)

multiplot(a, c, b, d, cols=2)

dev.off()
```
